CREATE OR REPLACE DATABASE STOCKS_MDS;
CREATE OR REPLACE SCHEMA STOCKS_MDS.COMMON;

CREATE OR REPLACE TABLE STOCKS_MDS.COMMON.bronze_stock_quotes_raw(
V VARIANT
);

SELECT * FROM STOCKS_MDS.COMMON.bronze_stock_quotes_raw;

